---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: fleet-alerts-monitor-watcher
rules:
  - apiGroups: ["fleet.cattle.io"]
    resources: ["bundledeployments", "gitrepos"]
    verbs: ["watch", "list", "get"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: fleet-alerts-monitor-watcher
subjects:
  - kind: ServiceAccount
    name: fleet-alerts-monitor
    namespace: cattle-fleet-system
roleRef:
  kind: ClusterRole
  name: fleet-alerts-monitor-watcher
  apiGroup: rbac.authorization.k8s.io
